export const LINK_LI_ACCOUNT = 'link_linkedin_account'
export const DISCONNECT_commentify_ACCOUNT = 'disconnect_commentify_account'
export const GET_PROFILE_DETAILS = 'get_profile_details'
export const GET_COOKIES = 'get_cookies'
export const GET_BROWSER_DETAILS = 'get_browser_details'
